### ISSUE TITLE
Writer is fine, missing reader ?

### ISSUE THREAD

**Issue by Firefly35** [stbrumme/toojpeg#10]
I found your library searching for in memory compression/decompression.
But toojpeg only supports writing the image, not the other way round.
Is there any plan to add the read method to the library ?

**Comment by stbrumme** [comment]
The library was always intended to be encoding-only. There are no plans to add any decoding.

**Comment by Firefly35** [comment]
I'd like to have the decoding part. If I start an implementation, would you
help if I need ?

Le mer. 24 nov. 2021 à 21:25, Stephan Brumme ***@***.***> a
écrit :

**Comment by stbrumme** [comment]
There is a huge amount of quirks in the JPEG/JFIF format as well as strange bugs in various encoders.
A decent decoder will be much bigger than my tiny encoder (which is just 666 lines of code) - I expect at least 2000 lines.

And even then you support only a minor subset of the JPEG format. Things such as arithmetic compression, progressive encoding etc. can be quite complex and tricky to get right.

So thank you for your offer to start such a decoder. But I will definitely not participate in such an endeavour.
