### ISSUE TITLE
Structure to represent colors

### ISSUE THREAD

**Issue by rathod-sahaab** [stbrumme/toojpeg#3]
why not use some thing like
```cpp
struct color_rgb {
    uint8_t r, g, b;
};
```
It would ease effort, as algorithms like `std::fill` and `std::generate` can be used.

**Comment by stbrumme** [comment]
There are tons of different input formats - at the moment my library only supports RGB.
However, my next major release will probably able to process other popular input formats, such as BGR and YUY2.

... and actually I don't see any reason why I should use std::fill or std::generate.
